FROM ubuntu:xenial

RUN apt-get update && apt install -y software-properties-common && \
	apt-get install -y build-essential gcc-7 g++-7 gcc g++ clang pkg-config \
		cmake python-pip git-core ccache curl
